const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const { createRequire } = require('node:module');
const path = require('node:path');
const lifecycle = require('../src/utils/sessionRequests');
const { geminiFixture: fixture } = require('./helpers/gemini-fixture');
test('typed Gemini uses selected HTTP model and session context without muting live audio', async () => {
    const f=fixture();
    const start=await f.handlers.get('initialize-gemini')(f.event,'test-key','','meeting','en-US','byok');
    assert.equal(start.success,true);
    const result=await f.handlers.get('send-text-message')(f.event,'What did we discuss?');
    assert.equal(result.success,true);
    assert.equal(f.generated[0].model,'selected-http-model');
    assert.match(f.generated[0].config.systemInstruction,/data pipelines/);
    assert.equal(f.realtime.length,0);
    assert.ok(f.events.some(([channel,payload])=>channel==='save-conversation-turn' && payload.turn.transcription==='What did we discuss?'));
    assert.ok(f.events.some(([channel,,metadata])=>channel==='new-response' && metadata.kind==='text'));
    lifecycle.closeSessionRequests();
});
test('Live saves final transcription only at turn completion and does not concatenate duplicate text modalities', async () => {
    const f=fixture();
    await f.handlers.get('initialize-gemini')(f.event,'test-key','','meeting','en-US','byok');
    f.callbacks.onmessage({serverContent:{inputTranscription:{text:'Question'},modelTurn:{parts:[{text:'Answer'}]},outputTranscription:{text:'Answer'},generationComplete:true}});
    assert.equal(f.events.filter(([channel])=>channel==='save-conversation-turn').length,0);
    f.callbacks.onmessage({serverContent:{outputTranscription:{text:' done'},turnComplete:true}});
    const saved=f.events.filter(([channel])=>channel==='save-conversation-turn');
    assert.equal(saved.length,1);
    assert.equal(saved[0][1].turn.ai_response,'Answer done');
    await f.handlers.get('close-session')(f.event);
    const count=f.events.length;
    f.callbacks.onmessage({serverContent:{modelTurn:{parts:[{text:'late'}]}}});
    assert.equal(f.events.length,count);
});
test('provider IPC rejects foreign frames and oversized typed requests', async () => {
    const f=fixture();
    const denied=await f.handlers.get('send-text-message')({...f.event,senderFrame:{}},'Hello');
    assert.equal(denied.success,false);
    const oversized=await f.handlers.get('send-text-message')(f.event,'x'.repeat(32001));
    assert.equal(oversized.success,false);
    assert.equal(f.generated.length,0);
});
